services:
  db:
    build: ./db
    container_name: library_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: librarydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - library_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d librarydb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build: ./app
    container_name: library_fastapi
    ports:
      - "8000:8000"  
    depends_on:
      db:
        condition: service_healthy
    networks:
      - library_network
    volumes:
      - ./app/src:/app 
    environment:
      DATABASE_URL: postgresql://user:${POSTGRES_PASSWORD}@db:5432/librarydb
    restart: unless-stopped

networks:
  library_network:
    driver: bridge

volumes:
  postgres_data: